---

- name: Add openrazer repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/openrazer/stable/ubuntu xenial main
    state: present

- name: install openrazer-meta
  package:
    name: openrazer-meta
    state: present

- name: ensure razerkbd module loaded
  modprobe:
    name: razerkbd
    state: present

- name: Creates xorg.conf.d directory
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: deploy X11 CAPSLOCK fix 
  register: xorgreload
  copy:
    src: 20-razer.conf
    dest: /etc/X11/xorg.conf.d/20-razer.conf

- name: reload Xorg
  command: killall -HUP Xorg
  when: xorgreload.changed
